sudo: false
language: node_js
node_js:
  - 'stable'
script:
  - npm run build
after_script:
  - ls -lh dist/*
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  on:
    branch: master
  file: dist/*
  file_glob: true
